
WITH FIRST_ECOLI AS (
    SELECT A.ID,
        IF(A.PARENT_ID IS NULL, 1, 0) AS 'FIRST'
    FROM ECOLI_DATA A
    JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID
    GROUP BY A.ID
    HAVING FIRST = 1
), SECOND_ECOLI AS (
    SELECT A.ID
    FROM ECOLI_DATA A
    JOIN FIRST_ECOLI B
    ON A.PARENT_ID = B.ID
)

SELECT A.ID
FROM ECOLI_DATA A
JOIN SECOND_ECOLI B
ON B.ID = A.PARENT_ID
ORDER BY A.ID
