-- 수원 지역의 연도 별 평균 미세먼지 오염도(PM_VAL1)와 평균 초미세먼지 오염도
SELECT YEAR(YM) AS "YEAR", ROUND(AVG(PM_VAL1),2) AS "PM10", ROUND(AVG(PM_VAL2),2) AS "PM2.5"
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원' AND LOCATION1 = '경기도'
GROUP BY YEAR(YM)
ORDER BY YEAR(YM) ASC
;