-- 코드를 입력하세요
SELECT A.USER_ID, A.PRODUCT_ID
FROM (
    SELECT COUNT(*) AS CNT, USER_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING CNT >=2
    ) A
ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC