SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT 
        ONLINE_SALE_ID AS SALES_ID,
        USER_ID,
        PRODUCT_ID,
        SALES_AMOUNT,
        SALES_DATE
    FROM ONLINE_SALE

    UNION ALL

    SELECT 
        OFFLINE_SALE_ID AS SALES_ID,
        NULL AS USER_ID,
        PRODUCT_ID,
        SALES_AMOUNT,
        SALES_DATE
    FROM OFFLINE_SALE
) T
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID