-- 코드를 입력하세요
-- 2022년 3월의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품ID, 유저ID, 판매량
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM (
	SELECT ONS.SALES_DATE, ONS.PRODUCT_ID, ONS.USER_ID, ONS.SALES_AMOUNT
    FROM ONLINE_SALE ONS
    WHERE YEAR(ONS.SALES_DATE) = '2022' AND MONTH(ONS.SALES_DATE) = '3'
    UNION ALL
    SELECT OFFS.SALES_DATE, OFFS.PRODUCT_ID, NULL AS USER_ID, OFFS.SALES_AMOUNT 
    FROM OFFLINE_SALE OFFS
    WHERE YEAR(OFFS.SALES_DATE) = '2022' AND MONTH(OFFS.SALES_DATE) = '3'
) AS S
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
;