WITH AVAILABLE_CARS AS (
    SELECT
        A.CAR_ID,
        A.CAR_TYPE,
        A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    WHERE A.CAR_TYPE IN ('세단', 'SUV')
      AND A.CAR_ID NOT IN (
          SELECT B.CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
          WHERE B.START_DATE <= '2022-11-30'
            AND B.END_DATE >= '2022-11-01'
      )
),
DISCOUNT_CARS AS (
    SELECT
        CAR_TYPE,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)
SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) AS FEE
FROM AVAILABLE_CARS A
JOIN DISCOUNT_CARS B
    ON A.CAR_TYPE = B.CAR_TYPE
WHERE FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) >= 500000
  AND FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) < 2000000
ORDER BY
    FEE DESC,
    A.CAR_TYPE ASC,
    A.CAR_ID DESC;