-- 코드를 작성해주세요
WITH RANKED_ECOLI AS (
    SELECT ID, SIZE_OF_COLONY,
        PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PCT_RANK
    FROM ECOLI_DATA
)
SELECT ID,
    CASE
        WHEN PCT_RANK <= 0.25 THEN 'CRITICAL'
        WHEN PCT_RANK <= 0.5 THEN 'HIGH'
        WHEN PCT_RANK <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED_ECOLI
ORDER BY ID
;