-- 코드를 입력하세요
SELECT USER_ID, 
    NICKNAME, 
    CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소",
    SUBSTR(TLNO,1,3) || '-' ||
    SUBSTR(TLNO,4,4) || '-' ||
    SUBSTR(TLNO,8)
    AS "전화번호"
FROM (
    SELECT WRITER_ID, COUNT(*)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
ORDER BY USER_ID DESC;