WITH YEAR_MONTH_TABLE AS (
    SELECT *, ROW_NUMBER() OVER(
        PARTITION BY YEAR(SALES_DATE), MONTH(SALES_DATE)
    ) AS RN
    FROM ONLINE_SALE 
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A
JOIN YEAR_MONTH_TABLE B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER