SELECT *, ROUND(PURCHASED_USERS/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'),1) AS PURCHASED_RATIO
FROM (
    SELECT YEAR(B.SALES_DATE) AS YEAR, 
        MONTH(B.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS 
    FROM USER_INFO A
    JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
    WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
    GROUP BY YEAR, MONTH
) T
ORDER BY YEAR, MONTH