SELECT HISTORY_ID,
    (DAILY_FEE * 
     (DATEDIFF(END_DATE, START_DATE)+1)) *
    (100 - IFNULL(T.DISCOUNT_RATE,0))/100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T
    ON A.CAR_TYPE = T.CAR_TYPE
   AND T.DURATION_TYPE = CASE
        WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL
   END
WHERE A.CAR_TYPE LIKE '%트럭%'
ORDER BY FEE DESC, HISTORY_ID DESC

