-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM CTE
    WHERE HOUR < 23
)

SELECT B.HOUR AS HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM ANIMAL_OUTS A
RIGHT OUTER JOIN CTE B
ON HOUR(A.DATETIME) = B.HOUR
GROUP BY B.HOUR
ORDER BY B.HOUR
;