# 리뷰 많이 작성한 순으로 정렬한 임시 테이블
WITH REVIEW AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
)
SELECT A.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
JOIN REST_REVIEW C
ON A.MEMBER_ID = C.MEMBER_ID
WHERE B.REVIEW_COUNT = (
    SELECT MAX(REVIEW_COUNT)
    FROM REVIEW
)
ORDER BY REVIEW_DATE, C.REVIEW_TEXT
;
