# -- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
JOIN (
    SELECT F.ITEM_ID
    FROM ITEM_INFO T
    JOIN ITEM_TREE F
    ON T.ITEM_ID = F.PARENT_ITEM_ID
    WHERE T.RARITY = 'RARE'
) B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC

