-- 코드를 입력하세요
-- 5회 이상 대여한 차량 정보 임시 테이블
WITH MORE_THAN_FIVE AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE,'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (SELECT CAR_ID FROM MORE_THAN_FIVE)
GROUP BY CAR_ID, EXTRACT(MONTH FROM START_DATE)
ORDER BY EXTRACT(MONTH FROM START_DATE) ASC, CAR_ID DESC
;