-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT DISTINCT A.ID
    FROM DEVELOPERS A
    JOIN SKILLCODES B
    ON A.SKILL_CODE & B.CODE = B.CODE
    WHERE B.NAME = 'Python' OR B.NAME = 'C#'
)
ORDER BY ID ASC
;