-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S_PYTHON ON S_PYTHON.NAME = 'Python'
JOIN SKILLCODES S_CSHARP ON S_CSHARP.NAME = 'C#'
WHERE (S_PYTHON.CODE & D.SKILL_CODE) != 0 OR (S_CSHARP.CODE & D.SKILL_CODE) != 0
ORDER BY D.ID
;