-- 코드를 작성해주세요
WITH MAX_SIZE_OF_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT YEAR(B.DIFFERENTIATION_DATE) AS YEAR, (A.MAX_SIZE - B.SIZE_OF_COLONY) AS YEAR_DEV, B.ID
FROM MAX_SIZE_OF_YEAR A
JOIN ECOLI_DATA B
ON A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;
