WITH MAX_LENGTH AS (
    SELECT ID, FISH_TYPE, LENGTH,
        ROW_NUMBER() OVER (
            PARTITION BY FISH_TYPE
            ORDER BY LENGTH DESC
        ) AS RN
    FROM FISH_INFO
)

SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM MAX_LENGTH A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE RN = 1
ORDER BY A.ID
