-- 2022년도 상하반기 점수 합 저장한 테이블
WITH SUM_SCORE AS (
    SELECT (A.SCORE + B.SCORE) AS SCORE, A.EMP_NO
    FROM HR_GRADE A
    JOIN HR_GRADE B
    ON A.EMP_NO = B.EMP_NO AND A.YEAR = B.YEAR
    WHERE A.HALF_YEAR = 1
    AND B.HALF_YEAR = 2
    AND A.YEAR = 2022
)


-- 평가 점수 가장 높은 사원 정보 출력
SELECT MAX(C.SCORE) AS SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_DEPARTMENT A
JOIN HR_EMPLOYEES B
ON A.DEPT_ID = B.DEPT_ID
JOIN SUM_SCORE C
ON B.EMP_NO = C.EMP_NO
WHERE B.POSITION = '팀원'
GROUP BY C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
ORDER BY SCORE DESC
LIMIT 1
;
