# -- 2022년도 상하반기 점수 합 저장한 테이블
# WITH SUM_SCORE AS (
#     SELECT (A.SCORE + B.SCORE) AS SCORE, A.EMP_NO
#     FROM HR_GRADE A
#     JOIN HR_GRADE B
#     ON A.EMP_NO = B.EMP_NO AND A.YEAR = B.YEAR
#     WHERE A.HALF_YEAR != B.HALF_YEAR
#     AND A.YEAR = 2022
# )


-- 평가 점수 가장 높은 사원 정보 출력
SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A
JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO, YEAR) B
ON A.EMP_NO = B.EMP_NO
ORDER BY B.SCORE DESC
LIMIT 1
;