-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE EXTRACT(YEAR FROM B.SALES_DATE) = '2022' AND EXTRACT(MONTH FROM B.SALES_DATE) = '01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC
;