-- 코드를 입력하세요
WITH MAX_PRICE_TBL AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY  
    ORDER BY MAX_PRICE DESC
)

SELECT A.CATEGORY, A.MAX_PRICE, B.PRODUCT_NAME
FROM MAX_PRICE_TBL A
JOIN FOOD_PRODUCT B
ON A.CATEGORY = B.CATEGORY AND A.MAX_PRICE=B.PRICE
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC
;