WITH RECURSIVE PRICE_GROUPS AS(
    SELECT 0 AS PRICE_GROUP
    
    UNION ALL
    
    SELECT PRICE_GROUP + 1
    FROM PRICE_GROUPS
    WHERE PRICE_GROUP < (
        SELECT FLOOR(PRICE/10000)
        FROM PRODUCT
        ORDER BY PRICE DESC
        LIMIT 1
    )
)


SELECT PRICE_GROUP* 10000 AS PRICE_GROUP,
    COUNT(P.PRICE) AS PRODUCTS
FROM PRICE_GROUPS PG
JOIN PRODUCT P
ON PG.PRICE_GROUP = FLOOR(PRICE/10000)
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP