-- 가격대 별 구간 생성
WITH CTE AS (
    SELECT 0 AS PRICE
    FROM DUAL
    UNION ALL
    SELECT LEVEL * 10000 AS PRICE
    FROM DUAL
    CONNECT BY LEVEL <= (
        SELECT CEIL(MAX(PRICE)/10000)
        FROM PRODUCT
    )
)
-- 가격대 별 상품 개수 집계
SELECT CTE.PRICE AS PRICE_GROUP, COUNT(B.PRODUCT_ID) AS PRODUCTS
FROM CTE
JOIN PRODUCT B
ON B.PRICE >= CTE.PRICE AND B.PRICE < CTE.PRICE+10000
GROUP BY CTE.PRICE
ORDER BY CTE.PRICE
;